# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Junteng Liu"
title_separator          : "-"
subtitle                 : ""
name                     : "Junteng Liu"
description              : "Junteng Liu's personal homepage"
url                      : "https://barn8nrisch.github.io"
baseurl                  : "/LJT-Homepage"
repository               : "barn8nrisch/LJT-Homepage"
teaser                   : 
logo                     : 
masthead_title           : 
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  # See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments for more details
  # The following are examples for different providers, uncomment and configure as needed
  # disqus:
  #   shortname           : "your-disqus-shortname"
  # discourse:
  #   server              : "meta.discourse.org"
  # facebook:
  #   appid               : "your-fb-app-id"
  #   num_posts           : 5 # default (5)
  #   colorscheme         : "light" # default (light)
  # utterances:
  #   repo                : ""
  #   issue_term          : ""
  #   label               : ""
  #   markup              : "" # default (null), "github" (deprecated), "gitlab" (deprecated), "username"
  # giscus:
  #   repo                : ""
  #   repo_id             : ""
  #   category_id         : ""
  #   mapping             : ""
  #   strict              : "0"
  #   reactions_enabled   : "1"
  #   emit_metadata      : "0"
  #   input_position    : "bottom" # default (bottom), "top"
  #   theme              : "light" # default (light), "dark", "preferred_color_scheme"
  #   lang               : "en" # default (en), "ar", "de", "es", "fa", "fr", "he", "it", "ja", "ko", "nl", "pl", "pt", "ru", "th", "tr", "uk", "vi", "zh-CN", "zh-TW"
  # custom:
  #   self_hosted        : false
  #   values:
  #     - name            : ""
  #       template        : ""
  #       site_key       : ""
  #       instance       : ""
  #       embed_code    : ""
  #       style          : ""
  #       class          : ""
  #       include       : ""
  #       exclude       : ""
  #       priority      : "0"
  #       enabled       : true

# Site Author
author:
  name             : "Junteng Liu"
  avatar           : 
  bio              : ""
  location         : 
  email            : "jliugi@connect.ust.hk"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - sftp-config.json
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Pagination
paginate: 5
paginate_path: /page:num/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Hong_Kong

# Atom Feed
atom_feed:
  path: atom.xml

# Search
search: true

# Analytics
analytics:
  provider: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
  - jekyll-archives
  - jekyll-github-metadata
  - jekyll-menus
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-titles-from-headings
  - jekyll-twitter-plugin
  - jekyll-watch
  - jekyll-youtube
